[package]
name = "http-server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.1"
reqwest = { version = "0.12.15", features = ["json"] }
tokio = { version = "1.44.1", features = ["full"] }
tower-http = { version = "0.6.3", features = ["fs"] }

[dev-dependencies]
tokio-test = "0.4.4"
